namespace Utilities.ActiveDirectory
{
    /// <summary>
    /// https://docs.microsoft.com/en-us/windows/desktop/ADSchema/c-user#windows-server-2012-attributes
    /// </summary>
    public interface IUser
    {
        //Account-Expires
        //ACS-Policy-Name
        //Address-Home
        //Admin-Count
        //audio
        //Bad-Password-Time
        //Bad-Pwd-Count
        //Business-Category
        //carLicense
        //Code-Page
        //Control-Access-Rights
        //DBCS-Pwd
        //Default-Class-Store
        //departmentNumber
        //Desktop-Profile
        //Dynamic-LDAP-Server
        //E-mail-Addresses
        //Employee-Number
        //Employee-Type
        //Given-Name
        //Group-Membership-SAM
        //Group-Priority
        //Groups-to-Ignore
        //Home-Directory
        //Home-Drive
        //Initials
        //jpegPhoto
        //labeledURI
        //Last-Logoff
        //Last-Logon
        //Last-Logon-Timestamp
        //Lm-Pwd-History
        //Locale-ID
        //Lockout-Time
        //Logon-Count
        //Logon-Hours
        //Logon-Workstation
        //Manager
        //Max-Storage
        //ms-COM-UserPartitionSetLink
        //MS-DRM-Identity-Certificate
        //ms-DS-AuthenticatedAt-DC
        //ms-DS-Cached-Membership
        //ms-DS-Cached-Membership-Time-Stamp
        //MS-DS-Creator-SID
        //ms-DS-Failed-Interactive-Logon-Count
        //ms-DS-Failed-Interactive-Logon-Count-At-Last-Successful-Logon
        //ms-DS-Last-Failed-Interactive-Logon-Time
        //ms-DS-Last-Successful-Interactive-Logon-Time
        //ms-DS-Primary-Computer
        //ms-DS-Resultant-PSO
        //ms-DS-Secondary-KrbTgt-Number
        //ms-DS-Site-Affinity
        //ms-DS-Source-Object-DN
        //ms-DS-Supported-Encryption-Types
        //ms-DS-User-Account-Control-Computed
        //ms-DS-User-Password-Expiry-Time-Computed
        //ms-IIS-FTP-Dir
        //ms-IIS-FTP-Root

        ms-IIS-FTP-Dir
ms-IIS-FTP-Root
MSMQ-Digests
MSMQ-Digests-Mig
MSMQ-Sign-Certificates
MSMQ-Sign-Certificates-Mig
msNPAllowDialin
msNPCallingStationID
msNPSavedCallingStationID
ms-PKI-AccountCredentials
ms-PKI-Credential-Roaming-Tokens
ms-PKI-DPAPIMasterKeys
ms-PKI-RoamingTimeStamp
msRADIUSCallbackNumber
ms-RADIUS-FramedInterfaceId
msRADIUSFramedIPAddress
ms-RADIUS-FramedIpv6Prefix
ms-RADIUS-FramedIpv6Route
msRADIUSFramedRoute
ms-RADIUS-SavedFramedInterfaceId
ms-RADIUS-SavedFramedIpv6Prefix
ms-RADIUS-SavedFramedIpv6Route
msRADIUSServiceType
msRASSavedCallbackNumber
msRASSavedFramedIPAddress
msRASSavedFramedRoute
msSFU-30-Name
msSFU-30-Nis-Domain
ms-TS-Allow-Logon
ms-TS-Broken-Connection-Action
ms-TS-Connect-Client-Drives
ms-TS-Connect-Printer-Drives
ms-TS-Default-To-Main-Printer
MS-TS-ExpireDate
MS-TS-ExpireDate2
MS-TS-ExpireDate3
MS-TS-ExpireDate4
ms-TS-Home-Directory
ms-TS-Home-Drive
ms-TS-Initial-Program
MS-TS-LicenseVersion
MS-TS-LicenseVersion2
MS-TS-LicenseVersion3
MS-TS-LicenseVersion4
MS-TSLS-Property01
MS-TSLS-Property02
MS-TS-ManagingLS
MS-TS-ManagingLS2
MS-TS-ManagingLS3
MS-TS-ManagingLS4
ms-TS-Max-Connection-Time
ms-TS-Max-Disconnection-Time
ms-TS-Max-Idle-Time
ms-TS-Primary-Desktop
ms-TS-Profile-Path
MS-TS-Property01
MS-TS-Property02
ms-TS-Reconnection-Action
ms-TS-Remote-Control
ms-TS-Secondary-Desktops
ms-TS-Work-Directory
Network-Address
Nt-Pwd-History
Operator-Count
Organization-Name
Other-Login-Workstations
Phone-Home-Primary
Phone-Mobile-Primary
Phone-Pager-Primary
photo

preferredLanguage
Preferred-OU
Primary-Group-ID
Profile-Path
Pwd-Last-Set
roomNumber
Script-Path
secretary
Service-Principal-Name
Terminal-Server
uid
Unicode-Pwd
User-Account-Control
User-Parameters
userPKCS12
User-Principal-Name
User-Shared-Folder
User-Shared-Folder-Other
User-SMIME-Certificate
User-Workstations
x500uniqueIdentifier
X509-Cert
    }
}
